dm = document.getElementById('dragme')
if not dm then console.log "No dm! Oh no!" else console.log "DM! "+dm


mouse_down = (event) ->
  if event.button == 1
    console.log "middle mouse down"

drag_start = (event) ->
  style = window.getComputedStyle(event.target, null)
  data = (parseInt(style.getPropertyValue('left')) - event.clientX) + "," +(parseInt(style.getPropertyValue('top')) - event.clientY)
  event.dataTransfer.setData('text/plain', data) #@data
  return

drag_over = (event) ->
  event.preventDefault()
  false

drop = (event) ->
  #A drop event must return a string with positional data.
  data = event.dataTransfer.getData('text/plain') #@data
  offset = data.split(',')
  dm.style.left = event.clientX + parseInt(offset[0], 10) + 'px'
  dm.style.top = event.clientY + parseInt(offset[1], 10) + 'px'
  event.preventDefault()
  false

wheel = (event) ->
  console.log event.deltaX+","+event.deltaY+","+event.deltaZ

move = (event) ->
  $(".drag").left = event.screenX;
  $(".drag").top = event.screenY;
  console.log event.screenX;

dm.addEventListener 'dragstart', drag_start, false
document.body.addEventListener 'dragover', drag_over, false
document.body.addEventListener 'drop', drop, false
document.body.addEventListener 'mousedown', mouse_down, false
document.body.addEventListener 'wheel', wheel, false
document.body.addEventListener 'mousemove', move, false

# ---
# generated by js2coffee 2.0.4
